Feature/#34 notificaciones
P2JN/doit pull request #112
Opened 2022-07-30 10:52 UTC by pedalopon

# Cambios
- Añadidas utilidades para generar notificaciones genéricas personalizadas
- Modificados los interceptores de creación y borrado para generar notificaciones
- Modificado el modelo de notificación añadido atributo faltante checked y ampliado el tamaño del campo titulo
# Endpoints a los que se les a añadido la notificación
- Creación/borrado de goal
- Creación/borrado de objetivo
- Creación/borrado de post
- Creación/borrado de participate
- Creación/borrado de tracking
- Cuando empiezas/dejas de seguir a un usuario(Notificación al usuario seguido no al que lo crea)
- Cuando das like a un post se notifica el like al creador del post
- Cuando das like a un tracking se notifica el like al creador del tracking
- Cuando comentas en un post se notifica al creador del post
- Cuando se completa un objetivo se notifica al usuario todos los objetivos completados y ademas si es colaborativo se les notifica a los usuarios que participasen en ese goal
# Ejemplo de formato de las notificaciones
{
	"notification": {
		"id": "62e4fb27467d32b8855a0e09",
		"title": "¡Has empezado a participar en este goal!",
		"content": "Empezaste a participar en el goal: Goal 6.",
		"creationDate": "2022-07-30T09:34:31.057302Z",
		"user": "62e2afd73a1380c95cace466"
	},
	"participate": {
		"id": "62e4fb25467d32b8855a0e08",
		"createdBy": "62e2afd73a1380c95cace466",
		"goal": "62e2afff3a1380c95cace4e7"
	}
}
Nota ademas destacar que en el caso del endpoint de progreso al poderse completar varios objetivos a la vez podrá devolver mas de una notificación
{
   "notification":[
      {
         "id":"62e50d430011229bdff4c044",
         "title":"Objetivo Anual completado",
         "content":"Has completado el objetivo Anual del goal Goal 14 creado el 2022-07-30 10:46:33.548000",
         "creationDate":"2022-07-30T10:51:47.874945Z",
         "user":"62e50baab6c1a3415ebeb139",
         "checked":false
      },
      {
         "id":"62e50d430011229bdff4c045",
         "title":"Objetivo Semanal completado",
         "content":"Has completado el objetivo Semanal del goal Goal 14 creado el 2022-07-30 10:46:33.548000",
         "creationDate":"2022-07-30T10:51:47.875997Z",
         "user":"62e50baab6c1a3415ebeb139",
         "checked":false
      }
   ],
   "progress":{
      "yearly":988.0,
      "weekly":988.0
   }
}

2022-07-30 19:50 UTC, JSnow11 commented on goals/views.py
> +        noti = notify_completed_objectives(progress, objectives, goal, user)
noti no parece un buen nombrado

2022-07-30 19:55 UTC, JSnow11 requested changes
Creo que deberíamos repensar un poco este procedimiento, rompe bastante con los viewSets ya implementados, ¿han sido todas las operaciones involucradas testeadas?

hablemos de ello antes de proceder

2022-07-30 19:55 UTC, JSnow11 commented on social/models.py
> +    title = fields.StringField(max_length=200, required=True)
deberiamos mantener el titulo corto y usar el contenido

2022-07-30 19:55 UTC, JSnow11 commented on social/serializers.py
> +        fields = ['id', 'title', 'content', 'creationDate', 'user', 'checked']
en realidad el checked da igual, las notificaciones van a ser más bien un "journal" un registro de actividad e interacciones, no se pueden borrar

2022-07-30 19:55 UTC, JSnow11 commented on social/views.py
> +                                 instance.createdBy.username + " te dio un like en tu tracking del " + str(instance.tracking.date)
en general tenemos q revisar los mensajes

2022-07-30 19:55 UTC, JSnow11 commented on utils/utils.py
> +
quizá mover todo esto a un nuevo fichero, notification.py? en utils folder?

2022-07-31 09:41 UTC, pedalopon commented on goals/views.py
> +        noti = notify_completed_objectives(progress, objectives, goal, user)
Variable renombrada

2022-07-31 09:44 UTC, pedalopon commented on social/models.py
> +    title = fields.StringField(max_length=200, required=True)
30 me parece muy corto para un titulo, tal vez 200 es excesivo.¿Que tal si lo dejamos en 50?

2022-07-31 09:46 UTC, pedalopon commented on social/serializers.py
> +        fields = ['id', 'title', 'content', 'creationDate', 'user', 'checked']
La idea que tenia esque tu desde el front muestres al iniciar sesión las notificaciones sin leer y el usuario en la sección de notificaciones pueda marcar como leído las que considere o todas de una vez.

2022-07-31 09:47 UTC, pedalopon commented on social/views.py
> +                                 instance.createdBy.username + " te dio un like en tu tracking del " + str(instance.tracking.date)
Si, como te comente son mensaje de test para la integración, luego deberíamos ponernos de acuerdo para ver que mensaje mostrar en cada tipo de modelo

2022-07-31 09:49 UTC, pedalopon commented on utils/utils.py
> +
Tenia pensado exactamente lo mismo, por ahora lo estaba posponiendo por si al final las notificaciones se implementaban de otra manera. Pero si, se moverán a un notifications.py adentro de la carpeta utils.

2022-07-31 10:48 UTC, JSnow11 commented on social/models.py
> +    title = fields.StringField(max_length=200, required=True)
Acordado 50

2022-07-31 10:51 UTC, JSnow11 commented on social/serializers.py
> +        fields = ['id', 'title', 'content', 'creationDate', 'user', 'checked']
Se usará checked para marcar las notificaciones como vistas, las que no tengan "checked" se contarán y mostrarán en una badge junto al icono

2022-07-31 10:51 UTC, JSnow11 commented on social/views.py
> +                                 instance.createdBy.username + " te dio un like en tu tracking del " + str(instance.tracking.date)
Revisados

2022-07-31 12:08 UTC, pedalopon commented on utils/utils.py
> +
Migrado a notifications.py

2022-08-03 21:41 UTC, JSnow11 commented
## bug backend

petición:

```
Request URL: http://localhost:8000/api/goal/62eae643504493f6e789234d/my-progress?user_id=62eae4c5504493f6e7892342
Request Method: GET
Status Code: 500 Internal Server Error
```

error:

```
unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
```

@pedalopon

2022-08-04 09:19 UTC, pedalopon commented
# Resolución
El bug ha sido arreglado se ha debido a una linea de código que ha sido sobrescrita en el merge

2022-08-04 19:41 UTC, JSnow11 requested changes
## bugs
- al trackear sobre un objetivo y volver a pedir el progreso, no hay variación (o no se registra o no se cuantifica)
- los mensajes deben ser uniformes, evtiar ":" y usar comillas para los títulos de las metas, posts ...

2022-08-04 20:07 UTC, pedalopon commented
# Resolucion 
- Se ha arreglado el bug de los trackeos diarios que derivaba del bug anterior
- Se han modificado os mensajes de las notificaciones para hacerlos mas uniformes

2022-08-05 16:06 UTC, JSnow11 commented
## errores
- typo: "objectivo"
- Semanal, Diario ... en mayus
- comillas también para cantidad y unidad registrada
- publicacion sin tilde
- "en esta meta", ¿en cual? mejor "en una meta"

2022-08-06 11:09 UTC, pedalopon commented
# Resolución 
- Se han corregido los errores en los mensajes de notificaciones
- Se ha modificado la notificación de completitud de objetivos para que ocurra durante la creación del tracking
- Se ha añadido un endpoint para obtener el numero de notificaciones sin leer

2022-08-06 11:54 UTC, JSnow11 approved these changes

2022-08-06 11:57 UTC, JSnow11 requested changes
## backend bug
- cuando se intenta hacer PATCH a una notificacion de objetivo completado se recibe el siguiente error:

```
'str' object has no attribute 'id'
```

@pedalopon

2022-08-06 14:07 UTC, JSnow11 approved these changes

2022-08-06 14:08 UTC, merged