#79-feat: Añadido comprobacion de que si el usuario es owner del obje…
P2JN/doit pull request #80
Opened 2022-07-20 16:26 UTC by pedalopon

# Cambios
- Añadida comprobación de seguridad para evitar operaciones update/delete sobre objetos que el usuario logeado no posea
# Test
- Intentar borrar/actualizar un objeto que no te pertenezca al usuario logeado y comprobar que salta un mensaje de error
- Intentar borrar/actualizar un objeto que le pertenezca al usuario logeado y comprobar que funciona correctamente
## Datos de apoyo para el test
A continuación dejo curls de operaciones sobre goal habria que probar con una id de un objeto que crees con la id del usuario logeado y otro con cualquier goal del populate por ejemplo
### POST
curl --request POST \
  --url http://localhost:8000/api/goal/ \
  --header 'Authorization: Token 381c56100ccced019173e9babd08b78ac3eea38e' \
  --header 'Content-Type: application/json'  \
  --data '{
    "title": "prueba3",
    "description": "gdsfsd",
    "unit": "m",
    "type": "GoalType.CHALLENGE",
 		"startDate": "2022-07-18T14:30:00Z",
    "deadline": "2022-07-21T14:30:00Z",
	"createdBy":"62d6fda0d6a900a121ff2f72"
}'
### DELETE
curl --request DELETE \
  --url http://localhost:8000/api/goal/62d6fa2b052b29ff693530c7/ \
  --header 'Authorization: Token d5f0400fee64e283b7cfab7434e705fda1888002'
### PUT
curl --request PUT \
  --url http://localhost:8000/api/goal/62d82c25b58f1738387926ba/ \
  --header 'Authorization: Token 381c56100ccced019173e9babd08b78ac3eea38e' \
  --header 'Content-Type: application/json' \
  --data '{
    "title": "update",
    "description": "gdsfsd",
    "unit": "m",
    "type": "GoalType.CHALLENGE",
 		"startDate": "2022-07-18T14:30:00Z",
    "deadline": "2022-07-21T14:30:00Z",
	"createdBy":"62d6fda0d6a900a121ff2f72"
}'
### GET
curl --request GET \
  --url http://localhost:8000/api/goal/ \
  --header 'Authorization: Token 381c56100ccced019173e9babd08b78ac3eea38e'

2022-07-21 15:52 UTC, JSnow11 commented
## review
- hay conflictos
- se podría elaborar una lista de los modelos en los que hay que cambiar "user" por "createdBy"?

2022-07-21 15:52 UTC, JSnow11 requested changes
review
hay conflictos
se podría elaborar una lista de los modelos en los que hay que cambiar "user" por "createdBy"?

2022-07-22 16:52 UTC, pedalopon commented
# Feedback 
- Se ha actualizado la rama resolviendo los conflictos
## Lista de modelos que se han cambiado el atributo user a createdBy
- LikeTracking
- LikePost
- Participate
- Tracking

2022-07-23 10:15 UTC, JSnow11 commented
## cambios
- añadida la actualización para el typo "tracking"

## preocupaciones
- el registro / login presenta problemas en esta rama
@pedalopon

2022-07-23 10:15 UTC, JSnow11 requested changes
## problemas
- el registro / login presenta problemas en esta rama

2022-07-23 10:23 UTC, pedalopon commented
# Problemas 
- falta adaptar la creacción de una participación en el frontend
![image](https://user-images.githubusercontent.com/61872564/180601226-0b8418be-837a-4842-af43-9376d24ef3c2.png)

2022-07-23 10:29 UTC, JSnow11 commented
> # Problemas
> * falta adaptar la creacción de una participación en el frontend
>   ![image](https://user-images.githubusercontent.com/61872564/180601226-0b8418be-837a-4842-af43-9376d24ef3c2.png)

Resuelto, listo para mergear

2022-07-23 10:29 UTC, JSnow11 approved these changes

2022-07-23 10:33 UTC, merged